[package]
name = "webremote"
version = "0.2.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["ws"] }
maud = { version = "0.27.0", features = ["axum"] }
tokio = { version = "1", features = ["full"] }
# evdev = "0.13.2"
